import AnimatedText from '@/components/AnimatedText'
import Education from '@/components/Education'
import Experience from '@/components/Experience'
import Layout from '@/components/Layout'
import Skills from '@/components/Skills'
import { useInView, useMotionValue, useSpring } from 'framer-motion'
import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect, useRef } from 'react'
import profileImg from "../../public/images/profile/profile.jpg"

const AnimatedNumber = ({ value }) => {
    const ref = useRef(null);

    const motionValue = useMotionValue(0);
    const springVal = useSpring(motionValue, { duration: 3000 });
    const isInView = useInView(ref, { once: true });

    useEffect(() => {
        if (isInView) {
            motionValue.set(value);
        }
    }, [isInView, value, motionValue]);

    useEffect(() => {
        springVal.on("change", (latest) => {
            if (ref.current && latest.toFixed(0) <= value) {
                ref.current.textContent = latest.toFixed(0);
            }
        })
    }, [springVal, value]);

    return <span ref={ref}></span>
}

const about = () => {
    return (
        <>
            <Head>
                <title>Gyan | About</title>
                <meta name="description" content="Generated by Gyan Prakash Kumar with the help of create next app" />
            </Head>
            <main className='flex w-full flex-col items-center justify-center'>
                <Layout className='pt-16'>
                    <AnimatedText text="Passion Fuels Purpose!" className='mb-16' />
                    <div className='grid w-full grid-cols-8 gap-16'>
                        <div className='w-full col-span-3 flex flex-col items-start justify-start'>
                            <h2 className='font-bold text-dark/75 uppercase text-lg mb-4'>Biography</h2>
                            <p className='font-medium'>
                                Hi, I'm tANJIRO, a Demon Slayer and Eldest child of my family with a passion for creating beautiful, functional, and user-centered digital experiences. With 4 years of experience in the field. I am always looking for new and innovative ways to bring my clients' visions to life.
                            </p>
                            <p className='font-medium my-4'>
                                I believe that design is about more than just making things look pretty - it's about solving problems and creating intuitive, enjoyable experiences for users.
                            </p>
                            <p className='font-medium'>
                                hether I'm working on a website, mobile app, or other digital product, I bring my commitment to design excellence and user-centered thinking to every project I work on. I look forward to the opportunity to bring my skills and passion to your next project.
                            </p>
                        </div>
                        <div className='border border-solid border-dark col-span-3 relative h-max rounded-2xl bg-light p-8'>
                            <div className='absolute top-0 -right-3 w-[102%] h-[103%] rounded-[2rem] -z-10 bg-dark' />
                            <Image src={profileImg} alt="profilePicture" className='w-full h-auto rounded-2xl' />
                        </div>
                        <div className='col-span-2 flex flex-col items-end justify-between'>
                            <div className='flex flex-col items-end justify-center'>
                                <span className='text-7xl font-bold inline-block'>
                                    <AnimatedNumber value={50} />+
                                </span>
                                <h2 className='text-xl font-medium text-dark/75 capitalize'>Satisfied Clients</h2>
                            </div>
                            <div className='flex flex-col items-end justify-center'>
                                <span className='text-7xl font-bold inline-block'>
                                    <AnimatedNumber value={40} />+
                                </span>
                                <h2 className='text-xl font-medium text-dark/75 capitalize'>Project Completed</h2>
                            </div>
                            <div className='flex flex-col items-end justify-center'>
                                <span className='text-7xl font-bold inline-block'>
                                    <AnimatedNumber value={5} />+
                                </span>
                                <h2 className='text-xl font-medium text-dark/75 capitalize'>Years of Experience</h2>
                            </div>
                        </div>
                    </div>
                    <Skills />
                    <Experience />
                    <Education />
                </Layout>
            </main>
        </>
    )
}

export default about
