import AnimatedText from '@/components/AnimatedText'
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React, { useRef } from 'react'
import { motion, useMotionValue } from 'framer-motion'
import article1 from '../../public/images/articles/pagination component in reactjs.jpg'
import article2 from '../../public/images/articles/create loading screen in react js.jpg'
import article3 from '../../public/images/articles/form validation in reactjs using custom react hook.png'

const FramerImage = motion(Image);

const ImgEffect = ({ title, img, link }) => {
    const x = useMotionValue(0);
    const y = useMotionValue(0);
    const imgRef = useRef(null);

    const handleMouseOn = (e) => {
        if (imgRef.current) {
            imgRef.current.style.display = 'inline-block';
            x.set(e.pageX);
            y.set(-10);
        }
    }


    const handleMouseOff = (e) => {
        // console.log(e.pageX);
        if (imgRef.current) {
            imgRef.current.style.display = 'none';
            x.set(0)
            y.set(0)
        }
    }

    return (
        <Link href={link} target='_blank'
            onMouseMove={handleMouseOn}
            onMouseLeave={handleMouseOff}
        >
            <h2 className='capitalize text-xl font-semibold hover:underline'>{title}</h2>
            <FramerImage
                style={{ x: x, y: y }}
                initial={{opacity: 0}}
                whileInView={{ opacity: 1, transition: { duration: 0.2 } }}
                ref={imgRef}
                src={img}
                alt={title}
                className='w-96 h-auto hidden absolute rounded-lg z-10' />
        </Link>
    )
}

const FeaturedArticle = ({ img, title, time, summary, link }) => {
    return (
        <li className='col-span-1 w-full p-4 bg-light border border-sold border-dark rounded-2xl relative'>
            <div className='absolute top-0 -right-3 w-[102%] h-[103%] rounded-[2.5rem] -z-10 bg-dark rounded-br-3xl' />
            <Link href={link} target='_blank' className='w-full inline-block cursor-pointer overflow-hidden rounded-lg'>
                <FramerImage whileHover={{ scale: 1.1 }} transition={{ duration: 0.2 }} src={img} alt={title} className='w-full h-auto' />
            </Link>
            <Link href={link} target='_blank'>
                <h2 className='my-2 capitalize text-2xl font-bold hover:underline mt-4 underline-offset-2'>{title}</h2>
            </Link>
            <p className='text-sm mb-2'>
                {summary}
            </p>
            <span className='text-primary font-semibold'>{time}</span>
        </li>
    )
}

const Article = ({ img, title, date, link }) => {
    return (
        <motion.li
            initial={{ y: 200 }}
            whileInView={{ y: 0, transition: { duration: 0.5, ease: 'easeInOut' } }}
            viewport={{once: true}}
            className='relative w-full p-4 py-6 my-4 rounded-xl flex items-center justify-between bg-light text-dark first:mt-0 border border-solid border-dark border-b-4 border-r-4 '
        >
            <ImgEffect title={title} img={img} link={link} />
            <span className='text-primary font-semibold pl-4'>{date}</span>
        </motion.li>
    )
}
const articles = () => {
    return (
        <>
            <Head>
                <title>Gyan | Articles</title>
                <meta name="description" content="Generated by Gyan Prakash Kumar with the help of create next app" />
            </Head>
            <main className='w-full flex flex-col items-center justify-center overflow-hidden mb-16'>
                <Layout className='pt-16'>
                    <AnimatedText text='Words Can Change The World! ' className='mb-16' />
                    <ul className='grid grid-cols-2 gap-16'>
                        <FeaturedArticle
                            title={'Build A Custom Pagination Component In ReactJs From Scratch'}
                            summary={'Learn how to build a custom pagination component in ReactJS from scratch. Follow this step-by-step guide to integrate Pagination component in your ReactJS project.'}
                            time={'9 min read'}
                            link='/'
                            img={article1}
                        />
                        <FeaturedArticle
                            title={'Creating Stunning Loading Screens In React: Build 3 Types Of Loading Screens'}
                            summary={'Learn how to create stunning loading screens in React with 3 different methods. Discover how to use React-Loading, React-Lottie & build a custom loading screen. Improve the user experience.'}
                            time={'10 min read'}
                            link='/'
                            img={article2}
                        />
                    </ul>
                    <h2 className='w-full font-bold text-4xl text-center my-16 mt-32'>More Articles</h2>
                    <Article
                        title={'Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling'}
                        date={'March 12, 2020'}
                        link={'/'}
                        img={article3}
                    />
                    <Article
                        title={'Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling'}
                        date={'March 12, 2020'}
                        link={'/'}
                        img={article3}
                    />
                    <Article
                        title={'Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling'}
                        date={'March 12, 2020'}
                        link={'/'}
                        img={article3}
                    />
                    <Article
                        title={'Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling'}
                        date={'March 12, 2020'}
                        link={'/'}
                        img={article3}
                    />
                </Layout>
            </main>
        </>
    )
}

export default articles
