import AnimatedText from '@/components/AnimatedText';
import HireMe from '@/components/HireMe';
import { LinkArrow } from '@/components/Icons';
import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import profileImg from "../../public/images/profile/profile.png";
import lightBulb from "../../public/images/svgs/lightBulb.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Gyan | Portfolio</title>
        <meta name="description" content="Generated by Gyan Prakash Kumar with the help of create next app" />
      </Head>
      <main className='flex items-center w-full min-h-screen text-dark'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full text-2xl'>
            <div className='w-1/2'>
              <Image src={profileImg} alt="profilePicture" className='w-full h-auto' />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText
                text="Turning Vision Into Reality Witth Code And Design"
                className='!text-6xl'
              />
              <p className='my-4 text-base font-medium '>
                As a skilled full-stck developer, I am dedicated to turning ideas into innovative web applications. Explore my latest projects and articles showcasing my experties in React.js and web development.
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link href='/dummy.pdf' target={'_blank'}
                  className='flex items-center p-2.5 bg-dark text-light px-6 text-lg font-semibold rounded-lg hover:bg-light hover:text-dark border brder-solid border-transparent hover:border-dark' download={true}
                >
                  Resume <LinkArrow className={'w-6 ml-1'} />
                </Link>
                <Link href='mailto:gyan_kr@yahoo.com' target={'_blank'}
                  className='ml-4 text-lg font-medium captilize text-dark underline'
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className='absolute right-8 bottom-8 inline-lock w-24'>
          <Image src={lightBulb} alt='lightBulb' className='w-full h-auto' />
        </div>
      </main>
    </>
  )
}
