import AnimatedText from '@/components/AnimatedText'
import { GithubIcon } from '@/components/Icons'
import Layout from '@/components/Layout'
import { motion } from 'framer-motion'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React from 'react'
import project1 from '../../public/images/projects/crypto-screener-cover-image.jpg'

const FramerImage = motion(Image);

const FeaturedProject = ({ type, title, summary, img, link, github }) => {
    return (
        <article
            className='w-full flex items-center justify-between rounded-3xl border border-solid border-dark bg-light shadow-2xl p-12 relative rounded-br-2xl'
        >
            <div
                className='absolute top-0 -right-3 w-[101%] h-[103%] rounded-[2.5rem] -z-10 bg-dark rounded-br-3xl'
            />
            <Link
                href={link}
                target='_blank'
                className='w-1/2 cursor-pointer overflow-hidden rounded-lg'
            >
                <FramerImage
                    src={img}
                    whileHover={{ scale: 1.1 }} transition={{ duration: 0.2 }}
                    alt={title}
                    className='w-full h-auto'
                />
            </Link>
            <div
                className='w-1/2 flex flex-col items-start justify-between pl-6'
            >
                <span
                    className='text-primary font-medium text-xl'
                >
                    {type}
                </span>
                <Link
                    href={link}
                    target='_blank'
                    className='hover:underline underline-offset-2'
                >
                    <h2 className='my-2 w-full text-left text-4xl font-bold'>{title}</h2>
                </Link>
                <p className='my-2 font-medium text-dark'>{summary}</p>
                <div className='mt-2 flex items-center justify-center'>
                    <Link href={github} target='_blank' className='w-10'> <GithubIcon /> </Link>
                    <Link href={github} target='_blank' className='ml-4 rounded-lg bg-dark text-light p-2 px-6 text-lg font-semibold'>Visit</Link>
                </div>
            </div>
        </article>
    )
}

const Project = ({ title, type, img, link, github }) => {
    return (
        <article
            className='flex flex-col items-center justify-center w-full rounded-2xl border border-solid border-dark relative bg-light p-6'
        >
            <div className='absolute top-0 -right-3 w-[102%] h-[103%] rounded-[2rem] -z-10 bg-dark rounded-br-3xl' />
            <Link href={link} target='_blank' className='w-full cursor-pointer overflow-hidden rounded-lg'>
                <FramerImage
                    src={img}
                    alt={title}
                    className='w-full h-auto'
                    whileHover={{ scale: 1.1 }} transition={{ duration: 0.2 }} />
            </Link>
            <div className='w-full flex flex-col items-start justify-between mt-4'>
                <span className='text-primary font-medium text-xl'>{type}</span>
                <Link href={link} target='_blank' className='hover:underline underline-offset-2' >
                    <h2 className='my-2 w-full text-left text-3xl font-bold'>{title}</h2>
                </Link>
                <div className='mt-2 flex justify-between w-full'>
                    <Link href={github} target='_blank' className='text-lg font-semibold underline underline-offset-2'>Visit</Link>
                    <Link href={github} target='_blank' className='w-8'> <GithubIcon /> </Link>
                </div>
            </div>
        </article>
    )
}

const projects = () => {
    return (
        <>
            <Head>
                <title>Gyan | Projects</title>
                <meta name="description" content="Generated by Gyan Prakash Kumar with the help of create next app" />
            </Head>
            <main className='w-full flex flex-col items-center justify-center mb-16'>
                <Layout className='pt-16'>
                    <AnimatedText text='Imagination Trumps Knowledge!' className='mb-16' />
                    <div className='grid grid-col-12 gap-24 gap-y-32'>
                        <div className='col-span-12'>
                            <FeaturedProject
                                title={'Crypto Screener Application'}
                                type={'Featured Project'}
                                summary={'A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your local currency.'}
                                img={project1}
                                link={'/'}
                                github={'/'}
                            />
                        </div>
                        <div className='col-span-6'>
                            <Project
                                title={'Crypto Screener Application'}
                                type={'Featured Project'}
                                img={project1}
                                link={'/'}
                                github={'/'}
                            />
                        </div>
                        <div className='col-span-6'>
                            <Project
                                title={'Crypto Screener Application'}
                                type={'Featured Project'}
                                img={project1}
                                link={'/'}
                                github={'/'}
                            />
                        </div>
                        <div className='col-span-12'>
                            <FeaturedProject
                                title={'Crypto Screener Application'}
                                type={'Featured Project'}
                                summary={'A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your local currency.'}
                                img={project1}
                                link={'/'}
                                github={'/'}
                            />
                        </div>
                        <div className='col-span-6'>
                            <Project
                                title={'Crypto Screener Application'}
                                type={'Featured Project'}
                                img={project1}
                                link={'/'}
                                github={'/'}
                            />
                        </div>
                        <div className='col-span-6'>
                            <Project
                                title={'Crypto Screener Application'}
                                type={'Featured Project'}
                                img={project1}
                                link={'/'}
                                github={'/'}
                            />
                        </div>
                    </div>
                </Layout>
            </main>
        </>
    )
}

export default projects
